[workspace]
resolver = "2"
members = ["examples/pam-http", "examples/pam-kv", "examples/pam-sober"]

[package]
name = "pam"
description = "PAM bindings for Rust"
version = "0.2.0"
authors = [ "Anthony Nowell <anowell@gmail.com>" ]
repository = "https://github.com/anowell/pam-rs"
readme = "README.md"
keywords = ["pam", "ffi", "linux", "authentication"]
license = "MIT"
edition = "2021"
build = "build.rs"

[dependencies]
libc = { version = "*" }
strum = { version = "0.24", features = ["derive"] }
bitflags = { version="^2", features = ["serde"] }
serde = { version="^1", optional=true, features=["derive"] }

[features]
default = ["std"]
std = []

[profile.release]
incremental = true
lto = "thin"
split-debuginfo = "packed"
strip = "debuginfo"

[profile.min-size-release]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "s"
split-debuginfo = "packed"
strip = "debuginfo"