[package]
name = "pam-http"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]
edition = "2021"

[lib]
name = "pam_http"
crate-type = ["cdylib"]

[dependencies]
pam-bindings = { version = "*", path = "../../" }
reqwest = { version = "0.11.27", features = ["blocking"] }
